---
language: php
php:
  - 5.6
  - 7.0

cache:
  directories:
    - ~/.composer/cache

sudo: false
dist: trusty

notifications:
  slack: codingdojoangola:C6WHKFX7G

install: composer install

before_script:
  - composer require codeclimate/php-test-reporter --dev

script:
  - vendor/bin/phpunit --debug

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#  - vendor/bin/test-reporter
